Bootstrap And Typos
redhat-beyond/Beyond-07-team-3 pull request #14
Opened 2022-03-11 22:39 UTC by MortarDefender

- bootstrap added to support smaller screens, and to beautify the site
- typos fixed in index.html and index_js.js

2022-03-13 14:23 UTC, brochwerger commented
README.md still has typos. Please review all English files

2022-03-15 08:52 UTC, brochwerger requested changes
Looks good but I noticed at least a couple of typos in README.md that haven't been fixed 
Architectue ? Datebase ?

Also, I think it is cleaner to separate the fixes of typos from styling changes (in .css) files.

2022-03-15 23:48 UTC, MortarDefender commented
Done. 
This PR is only for style change on the main site.
See a new PR for typos  #17

2022-03-16 10:41 UTC, MortarDefender commented
@YaelD @ravidbro @danninon @Yarboa @RonHachmon 
can you please write a code review on this pull request, 
see what has changed, and if there is a need to add or modify anything.
Thanks

2022-03-18 15:19 UTC, danninon submitted a review, later dismissed

2022-03-21 13:01 UTC, nemerna submitted a review, later dismissed

2022-03-21 13:01 UTC, nemerna commented on main/static/main/index_js.js
> +           "I'm a 4rd year Computer Science Student", ["I did a few courses that are relevant to the work we are going to do such as javascript and computer communications"])
please change 4rd to 4th

2022-03-21 13:06 UTC, brochwerger approved these changes, later dismissed

2022-03-21 13:11 UTC, nemerna commented on main/static/main/index_js.js
> +           "I'm a 4rd year Computer Science Student", ["I did a few courses that are relevant to the work we are going to do such as javascript and computer communications"])
You can also use this online tool to improve your writing.
Although it's not a necessity, I sometimes use it when I need to write official mail/requests.
https://www.wordtune.com/

2022-03-21 13:15 UTC, MortarDefender commented on main/static/main/index_js.js
> +           "I'm a 4rd year Computer Science Student", ["I did a few courses that are relevant to the work we are going to do such as javascript and computer communications"])
done

2022-03-21 13:19 UTC, nemerna approved these changes
Great!, i cant see any other typos/issues

2022-03-21 13:26 UTC, merged